trigger:
  branches:
    include:
      - master

resources:
- repo: self
  clean: true
  lfs: true

variables:
  IsLightBuild: $[eq(variables['Build.Reason'], 'PullRequest')]
  PackageOutputPath: $(Build.ArtifactStagingDirectory)
  NUGET_VERSION: 6.5.0
  macPoolName: 'macOS-12'
  ArtifactName: Binding.Intercom

stages:
- stage: Build

  jobs:
  - job : On_Mac
    strategy:
      maxParallel: 2
      matrix:
        Binding.Intercom:
          ApplicationPlatform: Any CPU

    pool:
      vmImage: $(macPoolName)
      
    workspace:
      clean: all

    steps:
      - template: build/steps-build.yml

- stage : Release
  condition: and(succeeded(), eq(variables['IsLightBuild'], 'false'))
  dependsOn: Build

  jobs:
  - template: build/steps-release.yml